# Generated by Django 5.2 on 2025-04-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ph', models.FloatField()),
                ('temperature', models.FloatField()),
                ('water_level_aquarium_cm', models.FloatField()),
                ('water_level_filterbak_cm', models.FloatField()),
            ],
        ),
    ]
